### ISSUE TITLE
Broken email address

### ISSUE THREAD

**Issue by davidhedlund** [meriac/openbeacon-ng#10]
get.openbeacon.org uses this link as email contact

> mailto:contact@openbeacon.org?subject=Physical%20Web%20on%20OpenBeacon

However, the email is broken, I got this message back: "Undeliverable: Physical Web on OpenBeacon"

Can you please update it?

**Comment by meriac** [comment]
@davidhedlund Thanks a lot for pointing it out! I just fixed it.

**Comment by davidhedlund** [comment]
Thanks.
