### ISSUE TITLE
About open beacon 

### ISSUE THREAD

**Issue by tamilhce** [meriac/openbeacon-ng#9]
The open beacon is amazing. I just  a have small question here, 
Is there are any mobile app to detect   openbeacon tags  as well as app to changes its UUID and payload. 
If  not, is it possible  to implement  it for openbeacons  tags ?

**Comment by MyerSmith** [comment]
I haven't tried openbeacon yet. 

Maybe https://f-droid.org/repository/browse/?fdid=com.samebits.beacon.locator works ?!
